### ISSUE TITLE
Trigger Error when using with Ember.js, solution proposed

### ISSUE THREAD

**Issue by wccsp** [BeSite/jQuery.mmenu#353]
I believe this is due to Ember.js extending the Array prototype. I also believe this could be fixed by using a For loop instead of a For In loop on line 246 in /src/js/jquery.mmenu.oncanvas.js.

I'm proposing a change from:

```
trigger: function()
		{
			var that = this,
				args = Array.prototype.slice.call( arguments ),
				evnt = args.shift();

			if ( this.cbck[ evnt ] )
			{
				for ( e in this.cbck[ evnt ] )
				{
					this.cbck[ evnt ][ e ].apply( that, args );
				}
			}
		},
```

to:

```
trigger: function()
		{
			var that = this,
				args = Array.prototype.slice.call( arguments ),
				evnt = args.shift();

			if ( this.cbck[ evnt ] )
			{
				for ( var i = 0; i < this.cbck[ evnt ].length; i++ )
				{
					this.cbck[ evnt ][ i ].apply( that, args );
				}
			}
		},
```

Thoughts?

**Comment by FrDH** [comment]
If Ember.js is extending the Array class which causes standard functionality to fail, Ember.js should fix that.

What's the error?

**Comment by wccsp** [comment]
The error is:

```
Uncaught TypeError: this.objectAt is not a function
```

This is due to the For In loop iterating over not only the methods passed in the 'init' callback array, but also the extended methods and properties of the Array prototype (from Ember.js).

I totally understand that this error is no fault of the jQuery mmenu plugin, but as this particular method is iterating over an array, it really should use a for loop (with 'for in' being used more for iterating over the properties of an object). 

From another thread on stackoverflow (http://stackoverflow.com/questions/242841/javascript-for-in-vs-for):

"the "for...in" does not work correctly for Arrays, as it will iterate over all Array properties and methods. Thus, you should use "for...in" only for iterating over object properties."

Also, a plain vanilla for loop has much better performance in most browsers anyways. So, I believe that by changing this one loop, it would not only solve my particular problem, but also improve compatibility with the plugin and other JS frameworks, improve performance, and stick to convention.

I'd be more than happy to submit a pull request if you're open to my suggestion.

Thanks for your help!

**Comment by FrDH** [comment]
I'll change the iteration later on.

**Comment by ayushshrestha** [comment]
i still have this issue can any one solve this problem
http://prntscr.com/c0iehf
